"""Shared constants for the CLI package."""

INDICATORS_YEAR_MIN = 2000
INDICATORS_YEAR_MAX = 3000

INFO_CAD_PAGE_DEFAULT = 1
INFO_CAD_PAGE_SIZE_DEFAULT = 20
INFO_CAD_PAGE_SIZE_MIN = 20
INFO_CAD_PAGE_SIZE_MAX = 1000